-- 0001_init down：逆序 DROP（含外键依赖，CASCADE 兜底）
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS service_calls CASCADE;
DROP TABLE IF EXISTS print_tasks CASCADE;
DROP TABLE IF EXISTS refunds CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS dishes CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS per_head_charges CASCADE;
DROP TABLE IF EXISTS bills CASCADE;
DROP TABLE IF EXISTS table_sessions CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS tables CASCADE;
DROP TABLE IF EXISTS table_areas CASCADE;
DROP TABLE IF EXISTS shops CASCADE;
